# The architecture names that yq uses differ from the names of the architecture
# that Ansible returns, so we have to translate certain names from the Ansible
# version to the yq version.
- name: define ansible to yq architecture mapping
  set_fact:
    ustreamer_yq_architecture_map:
      x86_64: amd64
      armv6l: arm
      armv7l: arm
      aarch64: arm64

- name: canonicalize yq binary architecture
  set_fact:
    ustreamer_yq_architecture: "{{ ustreamer_yq_architecture_map[ansible_architecture] | default(ansible_architecture) }}"

- name: install yq
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ ustreamer_yq_version }}/yq_linux_{{ ustreamer_yq_architecture }}"
    dest: /usr/bin/yq
    owner: root
    group: root
    mode: "0755"

- name: create uStreamer launcher directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ustreamer_user }}"
    group: "{{ ustreamer_group }}"
  loop:
    - "{{ ustreamer_launcher_dir }}"
    - "{{ ustreamer_launcher_configs_dir }}"

- name: create runtime variables dictionary
  set_fact:
    ustreamer_runtime_vars: {}

- name: collect non-null runtime variables
  set_fact:
    ustreamer_runtime_vars: "{{ ustreamer_runtime_vars | combine({ item: lookup('ansible.builtin.vars', item) }) }}"
  when: lookup('ansible.builtin.vars', item) != None
  loop:
    - ustreamer_port
    - ustreamer_video_path
    - ustreamer_encoder
    - ustreamer_format
    - ustreamer_resolution
    - ustreamer_desired_fps
    - ustreamer_workers
    - ustreamer_quality
    - ustreamer_brightness
    - ustreamer_persistent
    - ustreamer_use_dv_timings
    - ustreamer_drop_same_frames
    - ustreamer_tcp_nodelay
    - ustreamer_h264_sink
    - ustreamer_h264_sink_mode
    - ustreamer_h264_sink_rm
    - ustreamer_h264_bitrate

- name: print uStreamer runtime variables
  debug:
    var: ustreamer_runtime_vars

- name: write uStreamer runtime variables to file
  copy:
    dest: "{{ ustreamer_launcher_configs_dir }}/000-defaults.yml"
    content: "{{ ustreamer_runtime_vars | to_nice_yaml(explicit_start=True) }}"
    owner: "{{ ustreamer_user }}"
    group: "{{ ustreamer_group }}"
    mode: "0444"
  notify:
    - restart uStreamer

- name: install uStreamer launcher script
  copy:
    src: launch
    dest: "{{ ustreamer_launcher_script }}"
    owner: "{{ ustreamer_user }}"
    group: "{{ ustreamer_group }}"
    mode: "0755"
  notify:
    - restart uStreamer
