---
- name: install apt_key dependency
  apt:
    name: gnupg

- name: add archive apt repository key
  apt_key:
    url: https://ftp-master.debian.org/keys/archive-key-{{ ansible_distribution_major_version }}.asc
    state: present

- name: enable Janus apt suite
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ustreamer_janus_apt_suite }} main
    state: present

- name: install Janus package
  apt:
    name: janus
    default_release: "{{ ustreamer_janus_apt_suite }}"

- name: create Janus config files
  template:
    src: "{{ item }}.j2"
    dest: "{{ ustreamer_janus_configs_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - janus.transport.websockets.jcfg
  notify:
    - restart Janus

- name: install Janus config writer
  copy:
    src: write-janus-config
    dest: "{{ ustreamer_janus_dir }}/write-janus-config"
    owner: "{{ ustreamer_user }}"
    group: "{{ ustreamer_group }}"
    mode: "0755"
  notify:
    - write Janus configs
